# Generated by Django 4.2.5 on 2023-09-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleRank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('personId', models.CharField(max_length=8)),
                ('eventId', models.CharField(max_length=8)),
                ('best', models.IntegerField()),
                ('worldRank', models.IntegerField()),
                ('continentRank', models.IntegerField()),
                ('countryRank', models.IntegerField()),
            ],
        ),
    ]
