# Generated by Django 4.2.5 on 2023-10-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rankings", "0002_averagerank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="averagerank",
            name="personId",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="singlerank",
            name="personId",
            field=models.CharField(max_length=12),
        ),
    ]
