# Generated by Django 4.2.5 on 2023-10-05 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rankings", "0003_alter_averagerank_personid_alter_singlerank_personid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("countryId", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name="averagerank",
            name="personId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rankings.person"
            ),
        ),
        migrations.AlterField(
            model_name="singlerank",
            name="personId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rankings.person"
            ),
        ),
    ]
